#!/usr/bin/env python3
# /// script
# dependencies = ["huggingface_hub>=0.20.0"]
# ///

"""
Hub synchronisation utilities for HPO studies.

Provides functions for uploading and downloading Optuna study databases
to/from HuggingFace Hub for persistence and sharing.
"""

import json
from pathlib import Path
from typing import Optional

from huggingface_hub import HfApi, hf_hub_download


def sync_study_to_hub(
    local_path: str | Path,
    repo_id: str,
    study_name: str,
    private: bool = True,
    commit_message: str | None = None,
) -> str:
    """
    Upload a study database to HuggingFace Hub.

    Args:
        local_path: Path to the local SQLite database
        repo_id: Hub repository ID (e.g., "username/my-studies")
        study_name: Name of the study (used as filename)
        private: Whether to create a private repo
        commit_message: Optional commit message

    Returns:
        URL to the uploaded file
    """
    api = HfApi()

    # Ensure repo exists
    api.create_repo(
        repo_id=repo_id,
        repo_type="dataset",
        private=private,
        exist_ok=True,
    )

    # Upload the database file
    url = api.upload_file(
        path_or_fileobj=str(local_path),
        path_in_repo=f"{study_name}.db",
        repo_id=repo_id,
        repo_type="dataset",
        commit_message=commit_message or f"Update study: {study_name}",
    )

    return url


def download_study_from_hub(
    repo_id: str,
    study_name: str,
    local_dir: str | Path = "./optuna_studies",
) -> Path:
    """
    Download a study database from HuggingFace Hub.

    Args:
        repo_id: Hub repository ID
        study_name: Name of the study
        local_dir: Local directory to save to

    Returns:
        Path to the downloaded file
    """
    local_dir = Path(local_dir)
    local_dir.mkdir(exist_ok=True)

    local_path = hf_hub_download(
        repo_id=repo_id,
        filename=f"{study_name}.db",
        repo_type="dataset",
        local_dir=local_dir,
    )

    return Path(local_path)


def list_hub_studies(repo_id: str) -> list[str]:
    """
    List all studies in a Hub repository.

    Args:
        repo_id: Hub repository ID

    Returns:
        List of study names
    """
    api = HfApi()

    try:
        files = api.list_repo_files(repo_id=repo_id, repo_type="dataset")
        studies = [
            f.replace(".db", "")
            for f in files
            if f.endswith(".db")
        ]
        return studies
    except Exception:
        return []


def create_study_readme(
    repo_id: str,
    study_name: str,
    model: str,
    dataset: str,
    method: str,
    best_value: float | None = None,
    best_params: dict | None = None,
    n_trials: int = 0,
) -> str:
    """
    Create and upload a README for a study repository.

    Args:
        repo_id: Hub repository ID
        study_name: Study name
        model: Model being fine-tuned
        dataset: Dataset used
        method: Training method
        best_value: Best objective value
        best_params: Best hyperparameters
        n_trials: Number of completed trials

    Returns:
        URL to the README
    """
    api = HfApi()

    readme = f"""---
license: apache-2.0
tags:
- optuna
- hpo
- hyperparameter-optimization
- hpostudy-donotindex
- {method}
---

# HPO Study: {study_name}

Hyperparameter optimisation study for fine-tuning transformer models.

## Configuration

| Setting | Value |
|---------|-------|
| Model | `{model}` |
| Dataset | `{dataset}` |
| Method | {method.upper()} |
| Trials | {n_trials} |

"""

    if best_value is not None:
        readme += f"""## Best result

**Objective value:** {best_value:.6f}

"""

    if best_params:
        readme += """### Best hyperparameters

| Parameter | Value |
|-----------|-------|
"""
        for key, value in sorted(best_params.items()):
            if isinstance(value, float):
                readme += f"| {key} | {value:.6g} |\n"
            else:
                readme += f"| {key} | {value} |\n"

    readme += """
## Usage

```python
from huggingface_hub import hf_hub_download

# Download study database
local_path = hf_hub_download(
    repo_id="{repo_id}",
    filename="{study_name}.db",
    repo_type="dataset",
)

# Load with Optuna
import optuna
study = optuna.load_study(
    study_name="{study_name}",
    storage=f"sqlite:///{{local_path}}",
)

print(f"Best value: {{study.best_value}}")
print(f"Best params: {{study.best_params}}")
```

## Visualisation

Launch the dashboard:

```bash
python gradio_dashboard.py --hub {repo_id} --name {study_name}
```

---

*Generated by [optuna-hpo skill](https://github.com/huggingface/skills)*
""".format(repo_id=repo_id, study_name=study_name)

    # Upload README
    url = api.upload_file(
        path_or_fileobj=readme.encode("utf-8"),
        path_in_repo="README.md",
        repo_id=repo_id,
        repo_type="dataset",
        commit_message=f"Update README for {study_name}",
    )

    return url
