// Unrolled execution flow graph for the transformers-deep-review skill.
// Nodes are registry dimensions (D1-D41, see REVIEW_DIMENSIONS.md) plus terminal actions.
// Each edge is an OBSERVED causal transition mined from real maintainer review threads:
// a finding on `from` led the reviewer to check `to`. `n` = number of source PRs where
// the transition occurred; `prs` = provenance. Rendered by flowgraph.html.
//
// How a review agent uses this: after producing a finding on dimension X, walk the
// out-edges of X — they are the checks human reviewers ran next in the same situation.
// This complements execution_graph.js (static diff→dimension routing); it does not
// replace the all-41 DIMENSIONS coverage contract.
//
// Source trajectories (July 2026): model additions #43451, #46417, #41621, #44339;
// refactors #46818, #46738, #44174, #45028; fixes/mechanisms #46850, #47403, #46903,
// #43838; plus the skill's own run on #47365.

const FLOW = {
  version: "2026-07-24",
  source_prs: [43451, 46417, 41621, 44339, 46818, 46738, 44174, 45028, 46850, 47403, 46903, 43838, 47365],

  nodes: [
    { id: "D1", label: "Modular reuse / inheritance", kind: "dimension" },
    { id: "D2", label: "Decorator stack / output API", kind: "dimension" },
    { id: "D3", label: "Attention interface + QKV", kind: "dimension" },
    { id: "D4", label: "torch.compile safety", kind: "dimension" },
    { id: "D5", label: "Faithfulness / parity provenance", kind: "dimension" },
    { id: "D6", label: "Dead branches vs checkpoints", kind: "dimension" },
    { id: "D7", label: "Config discipline", kind: "dimension" },
    { id: "D8", label: "Layer-type taxonomy", kind: "dimension" },
    { id: "D9", label: "Signature stability / kwargs", kind: "dimension" },
    { id: "D10", label: "BC / deprecation / \u{1F6A8}", kind: "dimension" },
    { id: "D11", label: "Cross-model blast radius", kind: "dimension" },
    { id: "D12", label: "Test standards", kind: "dimension" },
    { id: "D13", label: "Naming pass", kind: "dimension" },
    { id: "D14", label: "Minimal surface / fail loudly", kind: "dimension" },
    { id: "D15", label: "Directness", kind: "dimension" },
    { id: "D16", label: "Loading/saving discipline", kind: "dimension" },
    { id: "D17", label: "State and hoisting", kind: "dimension" },
    { id: "D19", label: "Weight tying", kind: "dimension" },
    { id: "D20", label: "dtype/cast provenance", kind: "dimension" },
    { id: "D21", label: "Conversion + hub strategy", kind: "dimension" },
    { id: "D23", label: "Optional-backend gating", kind: "dimension" },
    { id: "D24", label: "Module containers", kind: "dimension" },
    { id: "D25", label: "Explicit path plans", kind: "dimension" },
    { id: "D26", label: "Return-type honesty", kind: "dimension" },
    { id: "D27", label: "Comment hygiene", kind: "dimension" },
    { id: "D28", label: "Docs/metadata coherence", kind: "dimension" },
    { id: "D29", label: "Measured Occam", kind: "dimension" },
    { id: "D30", label: "Coordination", kind: "dimension" },
    { id: "D31", label: "Framework mechanisms", kind: "dimension" },
    { id: "D32", label: "Feature isolation", kind: "dimension" },
    { id: "D33", label: "Hybrid cache/mask coverage", kind: "dimension" },
    { id: "D34", label: "Mask plumbing", kind: "dimension" },
    { id: "D35", label: "Tokenizer standards", kind: "dimension" },
    { id: "D36", label: "VLM composition", kind: "dimension" },
    { id: "D38", label: "Downstream consumability", kind: "dimension" },
    { id: "D41", label: "Distributed plans", kind: "dimension" },
    { id: "MRE", label: "build/demand minimal repro", kind: "action" },
    { id: "RUN_SLOW", label: "trigger slow CI (family scope)", kind: "action" },
    { id: "HUB_FIX", label: "fix belongs on the hub", kind: "action" },
    { id: "SPLIT_PR", label: "defer to a follow-up PR", kind: "action" },
    { id: "CONSOLIDATE_PR", label: "fix all siblings in one PR", kind: "action" },
    { id: "ROUTE_OWNER", label: "route to domain owner", kind: "action" },
    { id: "PARITY_RUN", label: "numerical parity check", kind: "action" },
    { id: "REBASELINE", label: "re-baseline expectations", kind: "action" }
  ],

  // Entry points observed in >=3 of the 13 source PRs (reviews opened on these).
  entries: ["D1", "D7", "D12", "D28", "D36"],

  edges: [
    { from: "D1", to: "D21", n: 4, why: "module identical up to weight names/fusing: rename/unfuse via conversion_mapping instead of a new class", prs: ["#43451", "#46417", "#44339", "#47365"] },
    { from: "D1", to: "D30", n: 3, why: "long PR drifts from main / collides with in-flight refactor: rebase or sync demanded", prs: ["#43838", "#43451", "#44339"] },
    { from: "D6", to: "D1", n: 3, why: "fake-optional branch or unused method: inherit the sibling that does it right", prs: ["#46818", "#46417", "#41621"] },
    { from: "D11", to: "RUN_SLOW", n: 3, why: "sibling sweep closes only via family-scoped run-slow", prs: ["#43838", "#46738", "#45028"] },
    { from: "D1", to: "D27", n: 2, why: "near-identical override kept: comment each divergence, restore parent comments", prs: ["#43838", "#44339"] },
    { from: "D5", to: "D14", n: 2, why: "original-implementation evidence wins; generalizing the option is rejected", prs: ["#43838", "#46738"] },
    { from: "D7", to: "D21", n: 2, why: "config attr renames block merge until conversion mappings checked", prs: ["#43838", "#46818"] },
    { from: "D7", to: "D11", n: 2, why: "one config fix triggers a sweep of every sibling config", prs: ["#46818", "#46417"] },
    { from: "D31", to: "D7", n: 2, why: "shared infra reading config attrs forces attribute_map standardization", prs: ["#46818", "#43838"] },
    { from: "D17", to: "D1", n: 2, why: "hoisting / compute-once rope enables verbatim modular copy from parent", prs: ["#46738", "#46417"] },
    { from: "D19", to: "D6", n: 2, why: "tying flag default challenged: delete the dead tied-weights mapping", prs: ["#43838", "#41621"] },
    { from: "D12", to: "D11", n: 2, why: "test skip or per-model copy challenged against siblings", prs: ["#46903", "#43451"] },
    { from: "D12", to: "D3", n: 2, why: "FA test skips: set the truthful capability flag instead of skipping", prs: ["#41621", "#43451"] },
    { from: "D21", to: "D12", n: 2, why: "released variants enumerated: one integration test per checkpoint", prs: ["#44339", "#41621"] },
    { from: "D7", to: "HUB_FIX", n: 2, why: "defaults/attribute values belong in the hub config, not code", prs: ["#43451", "#46417"] },
    { from: "D30", to: "D1", n: 2, why: "reviewer lands base/sibling simplification mid-review: PR must rebase and inherit it", prs: ["#43451", "#46417"] },
    { from: "D34", to: "D11", n: 1, why: "mask fix applied to whole gemma family: check the remaining sibling", prs: ["#46850"] },
    { from: "D11", to: "D34", n: 1, why: "if the family shares the pattern, move the fix into the internal mask creator", prs: ["#46850"] },
    { from: "D34", to: "D10", n: 1, why: "mask behavior change is breaking even if correct: \u{1F6A8} title", prs: ["#46850"] },
    { from: "D34", to: "RUN_SLOW", n: 1, why: "different masks per family member: reviewer self-triggers run-slow", prs: ["#46850"] },
    { from: "RUN_SLOW", to: "REBASELINE", n: 1, why: "expected slow-CI outputs change: re-baseline accepted at approval", prs: ["#46850"] },
    { from: "D20", to: "D21", n: 1, why: "per-forward de-interleaving: permute once in conversion mapping instead", prs: ["#47403"] },
    { from: "D21", to: "D5", n: 1, why: "conversion-time transform withdrawn on architecture evidence", prs: ["#47403"] },
    { from: "D5", to: "D12", n: 1, why: "parity fixture file: replace with in-test Expectations slices", prs: ["#47403"] },
    { from: "D31", to: "D12", n: 1, why: "easy-to-miss mechanism bug: repro must exist as a test", prs: ["#46903"] },
    { from: "D11", to: "D12", n: 1, why: "family-wide fix lands as one common test gated on config", prs: ["#46903"] },
    { from: "D11", to: "CONSOLIDATE_PR", n: 1, why: "fix all sibling models at once, not many tiny PRs", prs: ["#46903"] },
    { from: "D12", to: "D14", n: 1, why: "try/except in common test hides errors: fail loudly", prs: ["#46903"] },
    { from: "D12", to: "D15", n: 1, why: "hand-rolled test plumbing: use the tester helpers directly", prs: ["#46903"] },
    { from: "D5", to: "D1", n: 1, why: "parity mismatch (k_proj bias) fixed as a 3-line modular override", prs: ["#43838"] },
    { from: "D1", to: "D10", n: 1, why: "override accepted only if the parent model itself stays unchanged", prs: ["#43838"] },
    { from: "D3", to: "D1", n: 1, why: "attention structure decides the inheritance source (llama as gold standard)", prs: ["#43838"] },
    { from: "D28", to: "D29", n: 1, why: "docs pass exposes two models in one file: split question opened", prs: ["#43838"] },
    { from: "D29", to: "D31", n: 1, why: "split reversed once the head maps onto a generic framework layer", prs: ["#43838"] },
    { from: "D31", to: "D13", n: 1, why: "new generic-layer attr must carry a specific name", prs: ["#43838"] },
    { from: "D7", to: "D14", n: 1, why: "config branch simplified to a good default, no if/else", prs: ["#43838"] },
    { from: "D12", to: "MRE", n: 1, why: "device-map test failure: debug split percents before any skip", prs: ["#43838"] },
    { from: "MRE", to: "D27", n: 1, why: "undiagnosed failure tolerated only with a FIXME marking it", prs: ["#43838"] },
    { from: "MRE", to: "D31", n: 1, why: "reviewer-reproduced bug promoted to a native framework fix", prs: ["#43838"] },
    { from: "D30", to: "D29", n: 1, why: "in-flight-refactor collision answered with a benchmark", prs: ["#43838"] },
    { from: "D15", to: "D27", n: 1, why: "algorithmic processor code demands step comments + paper reference", prs: ["#43838"] },
    { from: "D9", to: "D1", n: 1, why: "signature mismatch resolved by a modular signature override (precedent named)", prs: ["#43838"] },
    { from: "D6", to: "D10", n: 1, why: "dropped format path questioned for breaking existing checkpoints", prs: ["#46818"] },
    { from: "D10", to: "D14", n: 1, why: "BC concern settled by a loud version-gated error", prs: ["#46818"] },
    { from: "D7", to: "D10", n: 1, why: "legacy attr removal rejected: keep reverse attribute mapping", prs: ["#46818"] },
    { from: "D41", to: "D1", n: 1, why: "repeated EP plans: inherit via modular instead of per-model copies", prs: ["#46818"] },
    { from: "D1", to: "D11", n: 1, why: "standardization question answered by cross-checking siblings", prs: ["#46818"] },
    { from: "D20", to: "ROUTE_OWNER", n: 1, why: "dequant/requant ordering deferred to the owning maintainer", prs: ["#46818"] },
    { from: "D32", to: "D10", n: 1, why: "moving code across modules is slightly breaking: \u{1F6A8}", prs: ["#46818"] },
    { from: "D14", to: "D10", n: 1, why: "warning dropped forces re-justifying the BC shim", prs: ["#46818"] },
    { from: "D8", to: "D10", n: 1, why: "layer-type taxonomy rename is breaking: \u{1F6A8}", prs: ["#46738"] },
    { from: "D8", to: "D11", n: 1, why: "new taxonomy: enumerate every model sharing the mechanism", prs: ["#46738"] },
    { from: "D8", to: "D33", n: 1, why: "layer-type renames must sync cache/config/mask mappings", prs: ["#46738"] },
    { from: "D8", to: "D38", n: 1, why: "distinct layer identities kept so vLLM can patch layers", prs: ["#46738"] },
    { from: "D13", to: "D8", n: 1, why: "naming alignment rejected: distinct mechanism keeps distinct type", prs: ["#46738"] },
    { from: "D1", to: "D3", n: 1, why: "inheriting llama imposes the canonical QKV pattern", prs: ["#46738"] },
    { from: "D3", to: "D5", n: 1, why: "rewritten attention re-checked against the original version", prs: ["#46738"] },
    { from: "D5", to: "D27", n: 1, why: "intentional divergence must carry an it's-intentional comment", prs: ["#46738"] },
    { from: "D3", to: "D9", n: 1, why: "attention standardization triggers signature policing", prs: ["#46738"] },
    { from: "D33", to: "D30", n: 1, why: "cache edits collide with in-flight cache refactor: coordinate", prs: ["#46738"] },
    { from: "D33", to: "D6", n: 1, why: "new cache branch challenged as unreachable", prs: ["#46738"] },
    { from: "D34", to: "D14", n: 1, why: "centralized mask correctness deletes per-model guards", prs: ["#46738"] },
    { from: "D1", to: "D12", n: 1, why: "modular-imported rewrite: test it to be sure", prs: ["#46738"] },
    { from: "D2", to: "D31", n: 1, why: "manual default plumbing checked against the framework decorator", prs: ["#46738"] },
    { from: "D4", to: "D27", n: 1, why: "compile flag must be explicit with the blocking reason", prs: ["#46738"] },
    { from: "D3", to: "D6", n: 1, why: "interface migration exposes now-dead helpers", prs: ["#46738"] },
    { from: "D12", to: "D29", n: 1, why: "proposed rule checked for evidence and redundancy first", prs: ["#44174"] },
    { from: "D26", to: "D2", n: 1, why: "legacy tuple branch forbidden: decorators own the conversion", prs: ["#44174"] },
    { from: "D19", to: "D16", n: 1, why: "tie_weights override corrupts loading: declare keys instead", prs: ["#44174"] },
    { from: "D12", to: "SPLIT_PR", n: 1, why: "fixing the skip-listed models deferred to another PR", prs: ["#44174"] },
    { from: "D1", to: "D6", n: 1, why: "modular silently emits unused classes: dead-class hunt", prs: ["#44174"] },
    { from: "D6", to: "SPLIT_PR", n: 1, why: "new dead-code rule deferred for simplicity", prs: ["#44174"] },
    { from: "D9", to: "D38", n: 1, why: "kwargs-through-attention tied directly to vLLM support", prs: ["#44174"] },
    { from: "D41", to: "D16", n: 1, why: "distributed features must not edit modeling files: patch at load", prs: ["#45028"] },
    { from: "D16", to: "D25", n: 1, why: "monkey-patch challenged: apply a plan instead", prs: ["#45028"] },
    { from: "D25", to: "D41", n: 1, why: "explicit ParallelStyle wins over implicit handling", prs: ["#45028"] },
    { from: "D27", to: "D6", n: 1, why: "why-are-we-touching-this exposes relics of an abandoned approach", prs: ["#45028"] },
    { from: "D41", to: "D6", n: 1, why: "design pivot triggers a hunt for leftovers", prs: ["#45028"] },
    { from: "D32", to: "D11", n: 1, why: "incidental removal checked against dependents: big regression found", prs: ["#45028"] },
    { from: "D11", to: "SPLIT_PR", n: 1, why: "regression + plan completion deferred to the next PR", prs: ["#45028"] },
    { from: "D41", to: "D23", n: 1, why: "torch import in config: protect it, configs are not torch-dependent", prs: ["#45028"] },
    { from: "D41", to: "D29", n: 1, why: "grad stitching / loading path: how much overhead? bench it", prs: ["#45028"] },
    { from: "D29", to: "ROUTE_OWNER", n: 1, why: "performance question escalated to the specialist", prs: ["#45028"] },
    { from: "D41", to: "D27", n: 1, why: "orally-explained mechanism must be written down", prs: ["#45028"] },
    { from: "D16", to: "D21", n: 1, why: "fused loading op challenged: not all checkpoints store it fused", prs: ["#45028"] },
    { from: "D16", to: "D12", n: 1, why: "new loading operation: update the loading tests", prs: ["#45028"] },
    { from: "D16", to: "D11", n: 1, why: "core extraction pushed back with a sibling counterexample", prs: ["#45028"] },
    { from: "D41", to: "D14", n: 1, why: "unused-rule warnings deleted; plan parsing already verifies", prs: ["#45028"] },
    { from: "D15", to: "D29", n: 1, why: "reuse suggestion declined after a worth assessment", prs: ["#45028"] },
    { from: "D1", to: "D5", n: 1, why: "reuse proposal answered by numerical-divergence analysis first", prs: ["#43451"] },
    { from: "D34", to: "D5", n: 1, why: "mask-helper reuse checked against original masking semantics", prs: ["#43451"] },
    { from: "D13", to: "D21", n: 1, why: "checkpoint-style weight names renamed at load, not in code", prs: ["#43451"] },
    { from: "D24", to: "D21", n: 1, why: "nn.Sequential split into layers; renames via conversion mapping", prs: ["#46417"] },
    { from: "D6", to: "D21", n: 1, why: "dead-branch suspicion resolved by reading the hub checkpoint config", prs: ["#43451"] },
    { from: "D21", to: "PARITY_RUN", n: 1, why: "unfusing weights changes numerics: gate on integration parity", prs: ["#44339"] },
    { from: "D28", to: "PARITY_RUN", n: 1, why: "docs claim quality needs PIL/eager: demand the quantified check", prs: ["#46417"] },
    { from: "D28", to: "D21", n: 1, why: "usage snippet cross-checked against hub README / chat template", prs: ["#43451"] },
    { from: "D28", to: "D14", n: 1, why: "explicit kwarg in a doc example: should it be the default?", prs: ["#46417"] },
    { from: "D36", to: "HUB_FIX", n: 1, why: "processor compensating for stale hub jinja: fix the template upstream", prs: ["#43451"] },
    { from: "D35", to: "HUB_FIX", n: 1, why: "hardcoded token ids: update the tokenizer on the hub", prs: ["#41621"] },
    { from: "D17", to: "HUB_FIX", n: 1, why: "runtime force-set of a processor value: save the correct hub config", prs: ["#41621"] },
    { from: "D6", to: "D36", n: 1, why: "None/ndim guard: verify the processor contract, delete the branch", prs: ["#43451"] },
    { from: "D6", to: "D12", n: 1, why: "branch serves only test fakes: fix the tests, not the code", prs: ["#46417"] },
    { from: "D6", to: "D38", n: 1, why: "duplicated attribute questioned: is it for vLLM or another dependent?", prs: ["#41621"] },
    { from: "D38", to: "ROUTE_OWNER", n: 1, why: "downstream access pattern needs a general solution: cc the owner", prs: ["#41621"] },
    { from: "D6", to: "D27", n: 1, why: "oddity that survives deletion must cite the original implementation", prs: ["#44339"] },
    { from: "D8", to: "D6", n: 1, why: "no layer_types in config: the mask-dict branch is unreachable", prs: ["#43451"] },
    { from: "D4", to: "D20", n: 1, why: "data-dependent branch traced to a dtype upcast: hoist the cast", prs: ["#43451"] },
    { from: "D7", to: "D20", n: 1, why: "fp32-attention config field rejected: upcast at call site", prs: ["#43451"] },
    { from: "D7", to: "D3", n: 1, why: "per-model attention switch in config: use the standard interface", prs: ["#43451"] },
    { from: "D7", to: "D36", n: 1, why: "module init'd from two configs: split into its own sub-model", prs: ["#43451"] },
    { from: "D36", to: "D4", n: 1, why: "feature scatter reviewed: .tolist() + branching flagged for compile", prs: ["#43451"] },
    { from: "D36", to: "D1", n: 1, why: "position-id logic in processor: move to modeling, copy the mrope sibling", prs: ["#46417"] },
    { from: "D11", to: "D10", n: 1, why: "sibling typo confirmed: reviewer opens the deprecation PR", prs: ["#46417"] },
    { from: "D11", to: "D27", n: 1, why: "until deprecation merges, the inconsistency carries a comment", prs: ["#46417"] },
    { from: "D9", to: "D11", n: 1, why: "signature hack traced to its origin model; removal proposed there too", prs: ["#41621"] },
    { from: "D26", to: "D38", n: 1, why: "tuple return flagged: downstream libs depend on ModelOutput", prs: ["#46417"] },
    { from: "D26", to: "D27", n: 1, why: "output class advertises fields it cannot produce: docstring must say so", prs: ["#44339"] },
    { from: "D7", to: "D19", n: 1, why: "tying flag duplicated across configs: establish which one controls", prs: ["#41621"] },
    { from: "D13", to: "D27", n: 1, why: "opaque short names kept: demand explanatory comments", prs: ["#44339"] },
    { from: "D7", to: "D27", n: 1, why: "config-check exception tolerated only with an attributing comment", prs: ["#44339"] },
    { from: "D24", to: "D1", n: 1, why: "Sequential chains refactored onto the parent's ConvNorm layer", prs: ["#44339"] },
    { from: "D1", to: "D7", n: 1, why: "inheritance blocked by loose args: move sizes into config to enable it", prs: ["#44339"] },
    { from: "D1", to: "ROUTE_OWNER", n: 1, why: "structure looks like a Backbone: cc the vision owner", prs: ["#44339"] },
    { from: "D1", to: "D13", n: 1, why: "converter prefix-matching forces renames before generation works", prs: ["#41621"] },
    { from: "D1", to: "MRE", n: 1, why: "claimed breakage: reviewer reproduces and tests the fix himself", prs: ["#41621"] },
    { from: "MRE", to: "D3", n: 1, why: "repro shows two eager attentions colliding: dedicated vision forward", prs: ["#41621"] },
    { from: "D12", to: "D2", n: 1, why: "CI failures triaged to a missing decorator", prs: ["#41621"] },
    { from: "D12", to: "D4", n: 1, why: "skipped compile test: preserve the compile path instead", prs: ["#43451"] },
    { from: "D12", to: "D27", n: 1, why: "every override or skip needs an inline reason", prs: ["#44339"] },
    { from: "D12", to: "RUN_SLOW", n: 1, why: "real checkpoint uncommented to trigger integration before core review", prs: ["#41621"] },
    { from: "D1", to: "D31", n: 1, why: "inheriting the parent PreTrainedModel sets the whole flags block", prs: ["#47365"] },
    { from: "D20", to: "PARITY_RUN", n: 1, why: "rope dtype differs from family: state the parity evidence", prs: ["#47365"] },
    { from: "D21", to: "RUN_SLOW", n: 1, why: "slow integration is the only real validation of a mapping entry", prs: ["#47365"] }
  ],

  // Flow shapes the edge list cannot express.
  notes: [
    "Two sinks dominate model additions: D1 (inherit it) and D21 (convert/rename it) — most findings terminate there; per-module D1 hits escalate to a whole-file modular_model_detector run.",
    "Sweep-then-gate: reviewers aggregate per-file markers into a D11 sibling list and close it only via family-scoped RUN_SLOW.",
    "SPLIT_PR is the release valve on refactors (late regressions spawn the next PR); CONSOLIDATE_PR is its inverse on bug sweeps (fix all siblings at once).",
    "Re-review loops are real: D12->D11->D12 (per-model test copies creep back), D13<->D8 naming oscillation, and the rebump loop — a resolved-but-unaddressed thread restarts its edge.",
    "D16 code placement can be a review PRECONDITION: content review starts only after the code moves to its module.",
    "Edges reverse on evidence: a D20->D21 prescription was withdrawn when D5 showed the layout was architectural.",
    "Unanswered asks escalate across maintainers on the same thread (question -> +1 -> imperative).",
    "When a model finding exposes a framework gap, reviewers fork the fix into its own PR rather than accept a model-side workaround (in-repo analogue of HUB_FIX)."
  ]
};

if (typeof window !== "undefined") window.FLOW = FLOW;
if (typeof module !== "undefined") module.exports = FLOW;
